services:
  web:
    build: .
    command: python manage.py runserver 0.0.0:8500
    volumes:
      - .:/app
    ports:
      - "8500:8500"
    depends_on:
      - db
  
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB={$POSTGRES_DB}
      - POSTGRES_USER={$POSTGRES_USER}
      - POSTGRES_PASSWORD={$POSTGRES_PASSWORD}
      - POSTGRES_PORT={$POSTGRES_PORT}

volumes:
  postgres_data: